var navList=[
    '<iframe class="iframe-show" src="../dataCenter/report.html"></iframe>',
    '<iframe class="iframe-show" src="../userManagement/logo.html"></iframe>',
    '<iframe class="iframe-show" src="../userManagement/terminalMember.html"></iframe>',
    '<iframe class="iframe-show" src="../userManagement/memberList.html"></iframe>',
    '<iframe class="iframe-show" src="../userManagement/roleManagement.html"></iframe>',
    '<iframe class="iframe-show" src="../stores/machine.html"></iframe>',
    '<iframe class="iframe-show" src="../stores/remote.html"></iframe>',
    '<iframe class="iframe-show" src="../goods/generalGoods.html"></iframe>',
    '<iframe class="iframe-show" src="../goods/customCategory.html"></iframe>',
    '<iframe class="iframe-show" src="../goods/customGoods.html"></iframe>',
    '<iframe class="iframe-show" src="../goods/goodsMaterial.html"></iframe>',
    '<iframe class="iframe-show" src="../merchants/merchantsList.html"></iframe>',
    '<iframe class="iframe-show" src="../merchants/Mymerchants.html"></iframe>',
    '<iframe class="iframe-show" src="../merchants/settlementDetails.html"></iframe>',
    '<iframe class="iframe-show" src="../accounts/machineAccounts.html"></iframe>',
    '<iframe class="iframe-show" src="../accounts/categoryAccounts.html"></iframe>',
    '<iframe class="iframe-show" src="../order/userOrder.html"></iframe>',
    '<iframe class="iframe-show" src="../order/oldOrder.html"></iframe>',
    '<iframe class="iframe-show" src="../advertising/fodder.html"></iframe>',
    '<iframe class="iframe-show" src="../advertising/release.html"></iframe>',
    '<iframe class="iframe-show" src="../my/open.html"></iframe>',
    '<iframe class="iframe-show" src="../my/binding.html"></iframe>',
    '<iframe class="iframe-show" src="../my/myInformation.html"></iframe>',
    '<iframe class="iframe-show" src="../my/ThePublic.html"></iframe>',
    '<iframe class="iframe-show" src="../operation/record.html"></iframe>',
]